version: '3.8'

services:
  nestapp:
    image: melipeano/back:latest
    ports:
      - "3001:3000"
    env_file:
      - .env.development
    depends_on:
      - postgresdb
    networks:
      - back_network


  postgresdb:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.development
    networks:
      - back_network
volumes:
  pgdata:
networks:
  back_network:
    driver: bridge